### ISSUE TITLE
Installation instructions are unclear

### ISSUE THREAD

**Issue by giray** [mschabhuettl/networkmanager-openconnect-sso#1]
Currently the installation instructions are unclear.   `standard procedure for building and installing a NetworkManager extension` is a bit vague if someone has not done this before.

Ideally step-by-step instructions would be provided, or an installer.  Alternatively the link to the "standard procedure" would be nice.

**Comment by mschabhuettl** [comment]
This repo is currently just a draft and very alpha. In case I've got time, I'm working on it ;-) I'll close the Issue if you don't mind, as the instruction will be updated, when the tool is actually written. ;-)
